version: '3.8'

services:
  multishock-api:
    build: .
    ports:
      - "5193:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./modules:/app/modules:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/v1/modules"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - multishock-network

networks:
  multishock-network:
    driver: bridge